In [1]:
help('modules')


Please wait a moment while I gather a list of all available modules...



Matplotlib is building the font cache; this may take a moment.
C:\Users\KLAUS\reptile\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
C:\Users\KLAUS\reptile\Lib\site-packages\nltk\twitter\__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn(
C:\Users\KLAUS\reptile\Lib\pkgutil.py:92: NumbaPendingDeprecationWarning: The 'pycc' module is pending deprecation. Replacement technology is being developed.

Pending Deprecation in Numba 0.57.0. For more information please see: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-the-numba-pycc-module
  __import__(info.name)
C:\Users\KLAUS\reptile\Lib\pkgutil.py:92: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(info.name)
C:\Users\KLAUS\reptile\Lib\site-packages\_distutils_hack\__init_

IPython             concurrent          mdurl               smtpd
OpenSSL             conda               menuinst            smtplib
PIL                 conda_build         mimetypes           snappy
PyQt5               conda_content_trust mistune             sndhdr
TBB                 conda_env           mkl                 sniffio
__future__          conda_index         mkl_fft             snowballstemmer
__hello__           conda_libmamba_solver mkl_random          socket
__phello__          conda_pack          mmap                socketserver
_abc                conda_package_handling mmapfile            socks
_aix_support        conda_package_streaming mmsystem            sockshandler
_argon2_cffi_bindings conda_token         modulefinder        sortedcontainers
_ast                conda_verify        more_itertools      soupsieve
_asyncio            configparser        mpmath              sphinx
_bisect             constantly          msgpack             spyder
_black_version   

In [1]:
import math

In [2]:
type(math.pi)

float

In [3]:
math.degrees(math.cos(60))

-54.56924413126439

In [4]:
math.sin(30)

-0.9880316240928618

In [5]:
# numpy vs in-built python lists

height = [1.8, 2.0, 1.5, 2.1]
weight = [45.5, 78.5, 67.7, 56.1]

# bmi = weight/ height**2

In [6]:
round(weight[0]/ height[0]**2, 2)

14.04

In [7]:
bmi = [round (w/h**2, 2) for w,h in zip(weight, height)]

In [8]:
bmi

[14.04, 19.62, 30.09, 12.72]

In [9]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [10]:
import numpy as np

In [11]:
from numpy import array

In [12]:
np_height = np.array(height)
np_weight = np.array(weight)

In [13]:
np_height


array([1.8, 2. , 1.5, 2.1])

In [14]:
np_weight

array([45.5, 78.5, 67.7, 56.1])

In [15]:
np_bmi = np.around(np_weight/ (np_height **2), 2)

In [18]:
np_bmi

array([14.04, 19.62, 30.09, 12.72])

In [19]:
bmi

[14.04, 19.62, 30.09, 12.72]

In [20]:
#indexing the array
np_bmi[0]

14.04

In [23]:
#slicing the array
np_bmi[1:3]

array([19.62, 30.09])

In [22]:
np_bmi[3:]

array([12.72])

In [24]:
np_bmi.mean()

19.1175

In [25]:
np_bmi.std()

6.843925682676573

In [26]:
np.std(np_bmi)

6.843925682676573

In [31]:
np.median(np_bmi)

16.83

In [32]:
np_bmi.shape

(4,)

In [33]:
type(np_bmi)

numpy.ndarray

In [37]:
multi_array = np.array([[14.04, 19.62, 30.09,12.72],
                        [14.04, 19.62, 30.09, 12.72],
                        [14.04, 19.62, 30.09, 12.72],
                       [14.04, 19.62, 30.09, 12.72]])

In [38]:
multi_array.shape

(4, 4)