In [49]:
#import pandas as pd

In [50]:
import numpy as np

In [51]:
ratings = np.array([[45, 85, 96], [74, 87, 32], [81, 45, 36]])
ratings

array([[45, 85, 96],
       [74, 87, 32],
       [81, 45, 36]])

In [52]:
ratings.shape

(3, 3)

In [53]:
ones = np.ones((5, 3))

In [54]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
ratings

array([[45, 85, 96],
       [74, 87, 32],
       [81, 45, 36]])

In [56]:
ratings[0, :]

array([45, 85, 96])

In [57]:
ratings[:, 0]

array([45, 74, 81])

In [58]:
np.random.randint(0, 10, (3,5))

array([[0, 2, 8, 2, 7],
       [1, 8, 0, 1, 7],
       [2, 4, 1, 0, 2]])

In [59]:
ratings

array([[45, 85, 96],
       [74, 87, 32],
       [81, 45, 36]])

In [60]:
ratings[0:2, 0:2]

array([[45, 85],
       [74, 87]])

In [61]:
ratings[ratings > 50]

array([85, 96, 74, 87, 81])

In [62]:
#appending and extra row

ratings_extra_row = np.append(ratings, [[84, 98, 97]], axis=0)

In [63]:
ratings_extra_row

array([[45, 85, 96],
       [74, 87, 32],
       [81, 45, 36],
       [84, 98, 97]])

In [66]:
ratings_extra_row2 = np.insert(ratings_extra_row, 0, [88, 78, 56])

In [67]:
ratings_extra_row2

array([88, 78, 56, 45, 85, 96, 74, 87, 32, 81, 45, 36, 84, 98, 97])

In [69]:
ratings_extra_row2.reshape((5,3))

array([[88, 78, 56],
       [45, 85, 96],
       [74, 87, 32],
       [81, 45, 36],
       [84, 98, 97]])

In [93]:
ratings_del_row = np.delete(ratings_extra_row2, [2], axis = 0)

In [80]:
ratings_del_row

array([88, 78, 45, 85, 96, 74, 87, 32, 81, 45, 36, 84, 98, 97])

In [82]:
ratings_extra_row2 = ratings_extra_row2.reshape((5,3))

In [83]:
ratings_extra_row2

array([[88, 78, 56],
       [45, 85, 96],
       [74, 87, 32],
       [81, 45, 36],
       [84, 98, 97]])

In [85]:
ratings_extra_row2.sum(axis=1)

array([222, 226, 193, 162, 279])

In [86]:
ratings_extra_row2.sum(axis=0)

array([372, 393, 317])

In [88]:
sales = np.arange(1,13).reshape(4,3)

In [89]:
sales

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [94]:
sales.sum(axis=1)

array([ 6, 15, 24, 33])